### ISSUE TITLE
Encounter failure in starting openethereum node

### ISSUE THREAD

**Issue by HaoyangLiu** [paritytech/parity-bridges-common#431]
Commands to build binaries and start openethereum node:
```shell scripts
git clone https://github.com/paritytech/openethereum.git
cd openethereum
git checkout 344991dbba2bc8657b00916f0e4b029c66f159e8 # the same to master branch
cargo +nightly-2020-10-04 build --all
./scripts/run-openethereum-node.sh
```

Error log:
```
Loading config file from /Users/liuhaoyang/workspace/rust/parity-bridges-common/deployments/dev/poa-config/poa-node-config
2020-10-23 11:30:47  main WARN engine  Running AuRa with a single validator implies instant finality. Use a database?
2020-10-23 11:30:47  main INFO openethereum::run  Starting OpenEthereum/v3.0.0-unstable-344991dbb-20200903/x86_64-apple-darwin/rustc1.49.0-nightly
2020-10-23 11:30:47  main INFO openethereum::run  Keys path ./deployments/dev/poa-config/keys/BridgePoa
2020-10-23 11:30:47  main INFO openethereum::run  DB path /tmp/oe-dev-node/chains/BridgePoa/db/a0942f8c45630089
2020-10-23 11:30:47  main INFO openethereum::run  State DB configuration: fast
2020-10-23 11:30:47  main INFO openethereum::run  Operating mode: active
2020-10-23 11:30:48  main INFO ethcore_service::service  Configured for BridgePoa using AuthorityRound engine
2020-10-23 11:30:48  main INFO openethereum::run  Running without a persistent transaction queue.
2020-10-23 11:30:48  main WARN openethereum::run  Updater is deprecated and may be removed in a future release. Please see #11696 for details:
https://github.com/openethereum/openethereum/issues/11696
2020-10-23 11:30:50  IO Worker #2 WARN engine  Running AuRa with a single validator implies instant finality. Use a database?
2020-10-23 11:30:50  IO Worker #2 DEBUG txqueue  Re-computing pending set for block: 0
2020-10-23 11:30:54  IO Worker #3 INFO network  Public node URL: enode://543d0874df46dff238d62547160f9d11e3d21897d7041bbbe46a04d2ee56d9eaf108f2133c0403159624f7647198e224d0755d23ad0e1a50c0912973af6e8a8a@1.182.141.179:30303
2020-10-23 11:30:55  IO Worker #2 WARN openethereum  Panic occurred, see stderr for details


====================

   0: backtrace::backtrace::libunwind::trace
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/capture.rs:128
   4: <std::ffi::c_str::CString as core::ops::drop::Drop>::drop
   5: panic_hook::set_with::{{closure}}
             at /Users/liuhaoyang/workspace/rust/openethereum/util/panic-hook/src/lib.rs:44
   6: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   7: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:153
   9: rust_begin_unwind
             at library/std/src/panicking.rs:483
  10: std::panicking::begin_panic
  11: std::panicking::begin_panic
  12: core::mem::uninitialized
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/core/src/mem/mod.rs:658
      linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174
  13: linked_hash_map::LinkedHashMap<K,V,S>::insert
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304
  14: lru_cache::LruCache<K,V,S>::insert
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/lru-cache-0.1.2/src/lib.rs:119
  15: state_db::StateDB::sync_cache
             at ethcore/state-db/src/lib.rs:231
  16: ethcore::client::client::Importer::commit_block
             at ethcore/src/client/client.rs:593
  17: <ethcore::client::client::Client as ethcore::client::traits::ImportSealedBlock>::import_sealed_block
             at ethcore/src/client/client.rs:2433
  18: ethcore::miner::miner::Miner::seal_and_import_block_internally::{{closure}}
             at ethcore/src/miner/miner.rs:732
  19: core::result::Result<T,E>::map
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/core/src/result.rs:508
  20: ethcore::miner::miner::Miner::seal_and_import_block_internally
             at ethcore/src/miner/miner.rs:728
  21: <ethcore::miner::miner::Miner as ethcore::miner::MinerService>::update_sealing
             at ethcore/src/miner/miner.rs:1274
  22: <ethcore::client::client::Client as client_traits::EngineClient>::update_sealing
             at ethcore/src/client/client.rs:2496
  23: authority_round::unix_now
  24: ethcore_io::worker::Worker::do_work
             at /Users/liuhaoyang/workspace/rust/openethereum/util/io/src/worker.rs:120
  25: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
             at /Users/liuhaoyang/workspace/rust/openethereum/util/io/src/worker.rs:93
  26: futures::future::loop_fn::loop_fn
             at /Users/liuhaoyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/loop_fn.rs:79
  27: ethcore_io::worker::Worker::new::{{closure}}
             at /Users/liuhaoyang/workspace/rust/openethereum/util/io/src/worker.rs:82
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/sys_common/backtrace.rs:137
  29: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/thread/mod.rs:464
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/panic.rs:308
  31: std::panicking::try::do_call
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/panicking.rs:381
  32: __rust_try
  33: std::panicking::try
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/panicking.rs:345
  34: std::panic::catch_unwind
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/panic.rs:382
  35: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/std/src/thread/mod.rs:463
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/core/src/ops/function.rs:227
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:87
  38: <unknown>
  39: <unknown>


Thread 'IO Worker #2' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H160, std::option::Option<account_state::Account>>` uninitialized, which is invalid', /rustc/25c8c53dd994acb3f4f7c02fe6bb46076393f8b0/library/core/src/mem/mod.rs:658

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2020-10-23 11:30:55  main INFO openethereum::run  Finishing work, please wait...
```

**Comment by tomusdrw** [comment]
@HaoyangLiu if the error also happens on the `master` branch it's a bug in the OpenEthereum itself, and it should be reported in the upstream repo.
To isolate the problem, I can only suggest to:
1. Try the latest version of upstream openethereum (https://github.com/openethereum/openethereum) - `master` branch
2. Try different compiler version - `stable` would be preferable.
