### ISSUE TITLE
PoA pallet benchmarks are broken

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#553]
```
====================

Version: 0.1.0

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   5: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
   7: pallet_bridge_eth_poa::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_bridge_eth_poa::Module<T,I>>::run_benchmark::{{closure}}
   8: pallet_bridge_eth_poa::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_bridge_eth_poa::Module<T,I>>::run_benchmark
   9: <rialto_runtime::Runtime as frame_benchmarking::utils::runtime_decl_for_Benchmark::Benchmark<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,rialto_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<rialto_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<rialto_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<rialto_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<rialto_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<rialto_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<rialto_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<rialto_runtime::Runtime>)>>>>::dispatch_benchmark
  10: rialto_runtime::api::dispatch
  11: std::thread::local::LocalKey<T>::with
  12: <rialto_bridge_node::service::Executor as sc_executor::native_executor::NativeExecutionDispatch>::dispatch
  13: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  14: sc_executor::wasm_runtime::RuntimeCache::with_instance
  15: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute
  18: frame_benchmarking_cli::command::<impl frame_benchmarking_cli::BenchmarkCmd>::run
  19: rialto_bridge_node::main
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: std::rt::lang_start::{{closure}}
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
      std::rt::lang_start_internal
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start


Thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `32`', /home/svyatonik/dev/parity-bridges-common/modules/ethereum/src/benchmarking.rs:141
```

**Comment by tomusdrw** [comment]
We should make sure we run benchmarks on the CI, at least in `master` or periodic builds.
